server:
  port: 90

datasource:
  host: "localhost:3306"
  user: "root"
  pass: "12345"
  dbname: "sgp_access_info_svc"

paths:
  getPersonalInfo: "/v1/sgp-info-svc/getPersonalInfo"

app-properties:
  getComorbidity:
    idStatusActive: 1
    idStatusInactive: 2