server:
  port: 93

datasource:
  host: "localhost:3306"
  user: "root"
  pass: "12345"
  dbname: "sgp_access_info_svc"

paths:
  getOnePersonalInfo: "/v1/sgp-access-info-svc/getOneInfoPersonal"
  getPersonalInfo: "/v1/sgp-access-info-svc/getInfoPersonal"
  getDocumentType: "/v1/sgp-access-info-svc/getDocumentType"
  getPersonalSex: "/v1/sgp-access-info-svc/getPersonalSex"

app-properties:
  getComorbidity:
    idStatusActive: 1
    idStatusInactive: 2
  getInfoPatient:
    dateBirth-Format: '02/01/2006'